### PR TITLE
No tinc release

### PR DESCRIPTION
**Pull request by cornelinux**

### CODE REVIEW

**Comment by plettich** [comment]
Maybe with https://github.com/privacyidea/tincparser/pull/5 we can use tinc again... tried it with ubuntu 16.04 and 18.04.

**Comment by plettich** [comment]
Re-added tinc by adding changes in https://github.com/privacyidea/tincparser/pull/5
@cornelinux could You check?

**Comment by cornelinux** [comment]
> Re-added tinc by adding changes in [privacyidea/tincparser#5](https://github.com/privacyidea/tincparser/pull/5)
> @cornelinux could You check?

will check it

**Comment by cornelinux** [comment]
> > Re-added tinc by adding changes in [privacyidea/tincparser#5](https://github.com/privacyidea/tincparser/pull/5)
> > @cornelinux could You check?
> 
> will check it

successfully tested on 18.04 :-)

**Pull request merged**
